Problem: use functions and variables from shared libraries
42ity/fty-warranty pull request #15
Opened 2018-08-03 13:46 UTC by bstepankova

Solution: select_asset_element_all_with_warranty_end is used from from fty-common-db
	  FTY_COMMON_LOGGING_DEFAULT_CFG is used from fty-common-logging
	  MLM_ENDPOINT is used from fty-common

Signed-off-by: Barbora Stepankova <BarboraStepankova@eaton.com>

2018-08-03 13:48 UTC, bstepankova commented
this PR needs new fty-common-db and tests will fail unless PR https://github.com/42ity/fty-common-db/pull/7 is merged and jenkins deployed with image containing the change

2018-08-08 12:24 UTC, jimklimov requested changes

2018-08-08 12:24 UTC, jimklimov commented on include/Makefile.am
> -#                               NOTE: Modified below!                          #
This. Explicitly. We have a documented procedure to regenerate zproject and reconcile with `git difftool` the inevitable manual changes in some files, marked as such. Follow it.

2018-08-08 12:24 UTC, jimklimov commented on packaging/debian/fty-warranty.install
> -### Note: this file was customized for paths
And this

2018-08-08 12:24 UTC, jimklimov commented on packaging/redhat/fty-warranty.spec
> -#    Note: This file was customized after generation; be sure to keep it so
And this

2018-08-08 12:34 UTC, jimklimov commented
Pushed the fixes (reversion of deletion of customized lines, while keeping the valid regenerated changes in those files) to same PR branch, hope that solves the issue. Note the PR should be "squashed" during merging, so git history of those customizations remains in place.

2018-08-08 16:23 UTC, jana-rapava approved these changes

2018-08-08 17:30 UTC, merged

2018-08-08 20:36 UTC, jimklimov commented
In the aftermath, thanks all for triggering the issues and investigation into them; a couple of issues in `zproject` and `gsl` are now in code review.